#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  ca.org.brt.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-brt
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org.brt.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/6d755c2cd72e1a9281259c407c25ca59bbf239755ac5ff1d47c37245bf8dc227_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org.brt.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/6d755c2cd72e1a9281259c407c25ca59bbf239755ac5ff1d47c37245bf8dc227_sk
    ports:
      - "7051:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./channel/crypto-config/peerOrganizations/org.brt.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./fabric-ca-server/ca-brt/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
    container_name: ca_brt

  ca.org.bus.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-bus
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org.bus.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/c229d489bd9c3f0f8e31681f5b264e1cb41aa62c3115ed3c2f8643cc07cdbf12_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org.bus.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/c229d489bd9c3f0f8e31681f5b264e1cb41aa62c3115ed3c2f8643cc07cdbf12_sk
    ports:
      - "7052:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./channel/crypto-config/peerOrganizations/org.bus.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./fabric-ca-server/ca-bus/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
    container_name: ca_bus

  ca.org.bank.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-bank
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org.bank.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/df817ba058eb68c3ead607e50fa3f113f37adb3a7e312317bc61e62d2f0bca6b_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org.bank.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/df817ba058eb68c3ead607e50fa3f113f37adb3a7e312317bc61e62d2f0bca6b_sk
    ports:
      - "7053:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./channel/crypto-config/peerOrganizations/org.bank.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./fabric-ca-server/ca-bank/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
    container_name: ca_bank

  ca.org.abt.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-abt
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org.abt.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/398a6eb552e77fcc058c8ffe0b981ab43a6016cbb22d5363f7ea081eda3843bd_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org.abt.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/398a6eb552e77fcc058c8ffe0b981ab43a6016cbb22d5363f7ea081eda3843bd_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./channel/crypto-config/peerOrganizations/org.abt.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./fabric-ca-server/ca-abt/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
    container_name: ca_abt
  
  zookeeper0:
        container_name: zookeeper0
        image: hyperledger/fabric-zookeeper
        environment:
            - ZOO_MY_ID=1
            - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
        ports:
            - 2181
            - 2888
            - 3888
  zookeeper1:
        container_name: zookeeper1
        image: hyperledger/fabric-zookeeper
        environment:
            - ZOO_MY_ID=2
            - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
        ports:
            - 2181
            - 2888
            - 3888
  zookeeper2:
        container_name: zookeeper2
        image: hyperledger/fabric-zookeeper
        environment:
            - ZOO_MY_ID=3
            - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
        ports:
            - 2181
            - 2888
            - 3888
  kafka0:
        image: hyperledger/fabric-kafka
        container_name: kafka0
        environment:
            - KAFKA_LOG_RETENTION_MS=-1
            - KAFKA_MESSAGE_MAX_BYTES=103809024
            - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
            - KAFKA_BROKER_ID=0
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
            - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
            - KAFKA_DEFAULT_REPLICATION_FACTOR=3
            - KAFKA_MIN_INSYNC_REPLICAS=2
        ports:
            - 9092
        depends_on:
            - zookeeper0
            - zookeeper1
            - zookeeper2
        links:
            - zookeeper0:zookeeper0
            - zookeeper1:zookeeper1
            - zookeeper2:zookeeper2
  kafka1:
        image: hyperledger/fabric-kafka
        container_name: kafka1
        environment:
            - KAFKA_LOG_RETENTION_MS=-1
            - KAFKA_MESSAGE_MAX_BYTES=103809024
            - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
            - KAFKA_BROKER_ID=1
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
            - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
            - KAFKA_DEFAULT_REPLICATION_FACTOR=3
            - KAFKA_MIN_INSYNC_REPLICAS=2
        ports:
            - 9092
        depends_on:
            - zookeeper0
            - zookeeper1
            - zookeeper2
        links:
            - zookeeper0:zookeeper0
            - zookeeper1:zookeeper1
            - zookeeper2:zookeeper2
  kafka2:
        image: hyperledger/fabric-kafka
        container_name: kafka2
        environment:
            - KAFKA_LOG_RETENTION_MS=-1
            - KAFKA_MESSAGE_MAX_BYTES=103809024
            - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
            - KAFKA_BROKER_ID=2
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
            - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
            - KAFKA_DEFAULT_REPLICATION_FACTOR=3
            - KAFKA_MIN_INSYNC_REPLICAS=2
        ports:
            - 9092
        depends_on:
            - zookeeper0
            - zookeeper1
            - zookeeper2
        links:
            - zookeeper0:zookeeper0
            - zookeeper1:zookeeper1
            - zookeeper2:zookeeper2
  kafka3:
        image: hyperledger/fabric-kafka
        container_name: kafka3
        environment:
            - KAFKA_LOG_RETENTION_MS=-1
            - KAFKA_MESSAGE_MAX_BYTES=103809024
            - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
            - KAFKA_BROKER_ID=3
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
            - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
            - KAFKA_DEFAULT_REPLICATION_FACTOR=3
            - KAFKA_MIN_INSYNC_REPLICAS=2
        ports:
            - 9092
        depends_on:
            - zookeeper0
            - zookeeper1
            - zookeeper2
        links:
            - zookeeper0:zookeeper0
            - zookeeper1:zookeeper1
            - zookeeper2:zookeeper2
  transactionO1.transactionorderer.com:
    container_name: transactionO1.transactionorderer.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt, /etc/hyperledger/crypto/brt/tls/ca.crt, /etc/hyperledger/crypto/bus/tls/ca.crt, /etc/hyperledger/crypto/bank/tls/ca.crt, /etc/hyperledger/crypto/abt/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 8051:7050
    volumes:
        - ./channel:/etc/hyperledger/configtx
        - ./channel/crypto-config/ordererOrganizations/transactionorderer.com/orderers/transactionO1.transactionorderer.com/:/etc/hyperledger/crypto/orderer
        - ./channel/crypto-config/peerOrganizations/org.brt.com/peers/peer0.org.brt.com/:/etc/hyperledger/crypto/brt
        - ./channel/crypto-config/peerOrganizations/org.bus.com/peers/peer0.org.bus.com/:/etc/hyperledger/crypto/bus
        - ./channel/crypto-config/peerOrganizations/org.bank.com/peers/peer0.org.bank.com/:/etc/hyperledger/crypto/bank
        - ./channel/crypto-config/peerOrganizations/org.abt.com/peers/peer0.org.abt.com/:/etc/hyperledger/crypto/abt
    depends_on:
            - kafka0
            - kafka1
            - kafka2
            - kafka3
  peer0.org.brt.com:
    container_name: peer0.org.brt.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org.brt.com
      - CORE_PEER_LOCALMSPID=BRTMSP
      - CORE_PEER_ADDRESS=peer0.org.brt.com:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbBrt:5984
    ports:
      - 9051:7051
      - 10001:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/org.brt.com/peers/peer0.org.brt.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - transactionO1.transactionorderer.com
      - couchdbBrt
  
  peer0.org.bus.com:
    container_name: peer0.org.bus.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org.bus.com
      - CORE_PEER_LOCALMSPID=BusMSP
      - CORE_PEER_ADDRESS=peer0.org.bus.com:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbBus:5984
    ports:
      - 9052:7051
      - 10002:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/org.bus.com/peers/peer0.org.bus.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - transactionO1.transactionorderer.com
      - couchdbBus
  
  peer0.org.bank.com:
    container_name: peer0.org.bank.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org.bank.com
      - CORE_PEER_LOCALMSPID=BankMSP
      - CORE_PEER_ADDRESS=peer0.org.bank.com:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbBank:5984
    ports:
      - 9053:7051
      - 10003:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/org.bank.com/peers/peer0.org.bank.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - transactionO1.transactionorderer.com
      - couchdbBank
  
  peer0.org.abt.com:
    container_name: peer0.org.abt.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org.abt.com
      - CORE_PEER_LOCALMSPID=ABTMSP
      - CORE_PEER_ADDRESS=peer0.org.abt.com:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbAbt:5984
    ports:
      - 9054:7051
      - 10004:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/org.abt.com/peers/peer0.org.abt.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - transactionO1.transactionorderer.com
      - couchdbAbt
  couchdbBrt:
    container_name: couchdbBrt
    image: hyperledger/fabric-couchdb
    ports:
      - 5984:5984
  couchdbBus:
    container_name: couchdbBus
    image: hyperledger/fabric-couchdb
    ports:
      - 6984:5984
  couchdbBank:
    container_name: couchdbBank
    image: hyperledger/fabric-couchdb
    ports:
      - 7984:5984
  couchdbAbt:
    container_name: couchdbAbt
    image: hyperledger/fabric-couchdb
    ports:
      - 8984:5984

  nginx:
    image: nginx
    ports:
      - "4001:80"
    volumes:
      - ../dapp-ui/static:/usr/share/nginx/html